/**
 * Markdown → real .pptx (Microsoft PowerPoint) generator.
 *
 * Builds a branded deck: a title slide, then a new content slide per top-level
 * heading (H1/H2), with the following paragraphs/bullets/tables placed on that
 * slide. Lower-level headings become bold lead-in lines. Designed for HR decks
 * (board updates, headcount reviews, policy roll-outs) generated from a chat
 * answer.
 */
import pptxgen from "pptxgenjs";
import { parseMarkdownBlocks, stripInline, inferTitle, type Block } from "@/lib/ai/documents/markdown-blocks";

const NAVY = "0F172A";
const BLUE = "2563EB";
const SLATE = "334155";

type SlideItem = { text: string; bold?: boolean; bullet?: boolean; indent?: number };

/** Group blocks into slides, starting a new slide at each H1/H2. */
function groupIntoSlides(blocks: Block[]): { title: string; items: SlideItem[]; table?: Extract<Block, { type: "table" }> }[] {
  const slides: { title: string; items: SlideItem[]; table?: Extract<Block, { type: "table" }> }[] = [];
  let current: { title: string; items: SlideItem[]; table?: Extract<Block, { type: "table" }> } | null = null;

  const ensure = (title: string) => {
    current = { title, items: [] };
    slides.push(current);
    return current;
  };

  for (const block of blocks) {
    if (block.type === "heading" && block.level <= 2) {
      ensure(block.text);
      continue;
    }
    if (!current) current = ensure("Overview");

    switch (block.type) {
      case "heading":
        current.items.push({ text: stripInline(block.text), bold: true });
        break;
      case "paragraph":
        current.items.push({ text: stripInline(block.text) });
        break;
      case "quote":
      case "callout":
        current.items.push({ text: stripInline(block.text), indent: 1 });
        break;
      case "bullets":
      case "numbered":
        for (const item of block.items) {
          current.items.push({ text: item.map((r) => r.text).join(""), bullet: true });
        }
        break;
      case "table":
        if (!current.table) current.table = block;
        break;
      default:
        break;
    }
  }

  return slides;
}

/** Generate a .pptx Buffer from Markdown content. */
export async function markdownToPptx(markdown: string, title: string): Promise<Buffer> {
  const blocks = parseMarkdownBlocks(markdown);
  const deckTitle = title || inferTitle(blocks, "Atlas Presentation");
  const slides = groupIntoSlides(blocks);

  const pptx = new pptxgen();
  pptx.author = "Atlas AI";
  pptx.title = deckTitle;
  pptx.layout = "LAYOUT_WIDE";

  // Title slide.
  const title0 = pptx.addSlide();
  title0.background = { color: NAVY };
  title0.addText(deckTitle, {
    x: 0.6,
    y: 2.2,
    w: 12.1,
    h: 1.8,
    fontSize: 40,
    bold: true,
    color: "FFFFFF",
    align: "left",
  });
  title0.addText("Generated by Atlas AI", { x: 0.6, y: 4.1, w: 12, h: 0.5, fontSize: 14, color: "93C5FD" });

  for (const slide of slides) {
    const s = pptx.addSlide();
    s.addText(slide.title, { x: 0.5, y: 0.3, w: 12.3, h: 0.8, fontSize: 26, bold: true, color: NAVY });
    s.addShape(pptx.ShapeType.line, { x: 0.5, y: 1.15, w: 12.3, h: 0, line: { color: BLUE, width: 2 } });

    if (slide.table) {
      const rows = [
        slide.table.headers.map((h) => ({
          text: h,
          options: { bold: true, color: "FFFFFF", fill: { color: NAVY } },
        })),
        ...slide.table.rows.map((r) => r.map((c) => ({ text: c, options: { color: SLATE } }))),
      ];
      s.addTable(rows, { x: 0.5, y: 1.4, w: 12.3, fontSize: 12, border: { type: "solid", color: "E2E8F0", pt: 1 } });
    } else if (slide.items.length) {
      const textRuns = slide.items.map((it) => ({
        text: it.text,
        options: {
          bullet: it.bullet ? true : false,
          bold: it.bold,
          indentLevel: it.indent ?? 0,
          fontSize: it.bold ? 17 : 15,
          color: it.bold ? NAVY : SLATE,
          paraSpaceAfter: 6,
        },
      }));
      s.addText(textRuns, { x: 0.6, y: 1.4, w: 12.1, h: 5.6, valign: "top" });
    }
  }

  // pptxgenjs returns the requested output type; "nodebuffer" yields a Buffer.
  const out = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
  return out;
}
